[package]
name = "otap-df-otlp"
description = "OTLP nodes"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
otap-df-engine = { path = "../engine" }
otap-df-channel = { path = "../channel" }
prost = "0.13.4"
tonic = { version = "0.12.3", default-features = false, features = [
    "server",
    "codegen",
    "prost",
    "tls",
    "tls-roots",
] }
thiserror.workspace = true
serde_json.workspace = true
tokio.workspace = true
async-trait.workspace = true

[build-dependencies]
tonic-build = { version = "0.13.0", features = ["cleanup-markdown"] }

